### ISSUE TITLE
 yum localinstall poplog-0.1-2.x86_64.rpm returns an error

### ISSUE THREAD

**Issue by throatwobblermangrove3** [GetPoplog/Seed#22]
@sfkleach 

### What happened?

The poplog-0.1-2.x86_64.rpm does not install

### Steps To Reproduce

1. Obtain poplog-0.1-2.x86_64.rpm and scp to a fedora-33-server.x86-64 vm on DO server
2. ssh to vm
3. As root, try to install the package the package . The command is:

yum localinstall poplog-0.1-2.x86_64.rpm 

4. Observe the yum output and error messages.  Next lines are a snippet at the end which shows the problem.
5. 
[root@localhost ~]# yum localinstall poplog-0.1-2.x86_64.rpm 
Fedora 33 openh264 (From Cisco) - x86_64                                                                                                             5.9 kB/s | 2.5 kB     00:00    
Fedora Modular 33 - x86_64                                                                                                                           195 kB/s | 3.3 MB     00:17    
Fedora Modular 33 - x86_64 - Updates                                                                                                                 2.5 MB/s | 3.1 MB     00:01    
Fedora 33 - x86_64 - Updates                                                                                                                          22 MB/s |  28 MB     00:01    
Fedora 33 - x86_64                                                                                                                                    23 MB/s |  72 MB     00:03    
Error: 
 Problem: conflicting requests
  - nothing provides libtinfo.so.6(NCURSES6_TINFO_5.0.19991023)(64bit) needed by poplog-0.1-2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

###  Kernel & Operating System Information

[root@localhost ~]# yum localinstall poplog-0.1-2.x86_64.rpm 
Fedora 33 openh264 (From Cisco) - x86_64                                                                                                             5.9 kB/s | 2.5 kB     00:00    
Fedora Modular 33 - x86_64                                                                                                                           195 kB/s | 3.3 MB     00:17    
Fedora Modular 33 - x86_64 - Updates                                                                                                                 2.5 MB/s | 3.1 MB     00:01    
Fedora 33 - x86_64 - Updates                                                                                                                          22 MB/s |  28 MB     00:01    
Fedora 33 - x86_64                                                                                                                                    23 MB/s |  72 MB     00:03    
Error: 
 Problem: conflicting requests
  - nothing provides libtinfo.so.6(NCURSES6_TINFO_5.0.19991023)(64bit) needed by poplog-0.1-2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by sfkleach** [comment]
The problem with ncurses has been tracked down and eliminated. This should be resolved.
